보안 뉴스 피드 구현 완료
reum/pyTelegramBotAPI pull request #15
Opened 2016-11-22 08:41 UTC by reum

#2 구현 완료 했어요. 하지만 자신이 없음 또륵 ;ㅅ; 피드백 부탁해요

2016-11-22 15:26 UTC, sweetchipsw commented on telebot/sejong/news.py
> +    issue = urllib.urlopen('http://www.dailysecu.com/rss/S1N1.xml').read()
urllib 에서 Exception 처리해야 오류가 안날것 같아요

2016-11-22 15:28 UTC, sweetchipsw commented on telebot/sejong/news.py
> +        print i
print는 콘솔에 출력이므로 추후 실적용시는 return 으로 하셔야 할것 같네요

2016-11-22 15:28 UTC, sweetchipsw commented on telebot/sejong/news.py
> +    if command == news_issue:
news_issue 와 new_popular의 변수가 정의되어 있지 않은데 이 부분은 수정해주셔야 할듯요.

2016-11-22 15:38 UTC, jsh95311 approved these changes
오류가 있어보입니다. 수정 부탁드려요

2016-11-22 15:38 UTC, jsh95311 commented on telebot/sejong/news.py
getNews() 함수에서 출력대신 return을 해줘야 할 것 같습니다.
그리고 return에서 딕셔너리를 넘겨주고, "링크"혹은 "[",title,"]"와 같이 문자열 포멧팅은 caller 에서 처리를 해줄 수 있도록 해야할 것 같아요.

2016-11-22 15:38 UTC, jsh95311 commented on telebot/sejong/news.py
news_issue, news_popular가 초기화 되지 않았습니다.

2016-11-22 15:38 UTC, jsh95311 commented on telebot/sejong/news.py
issue와 popular의 urlopen 값을 먼저 호출한 다음(8~9 줄)에 11~14 줄에서 둘 중 하나만 선택하면 비효율 적인것 같습니다. 
r = 넣는 부분에서 urlopen 도 같이 수행해야 할 것 같아요.

2016-11-22 15:39 UTC, jsh95311 requested changes
오류가 있어보입니다. 수정 부탁드려요

2016-11-22 16:31 UTC, reum commented on examples/sejong/test.py
> +print news.getNews(popular)
임의로 넣어둔거에요! 나중에 인기뉴스 혹은 최신뉴스에 대한 옵션을 인자로 넘겨야해서! ㅎㅎ

2016-11-22 16:32 UTC, reum commented on telebot/sejong/news.py
> +    issue = urllib.urlopen('http://www.dailysecu.com/rss/S1N1.xml').read()
알겠쯥니다

2016-11-22 16:32 UTC, reum commented on telebot/sejong/news.py
> +    if command == news_issue:
아 그거 string으로 넣는다는걸 그만...ㅎ 고칠게여

2016-11-22 16:33 UTC, reum commented on telebot/sejong/news.py
> +        print i
얍얍

2016-11-22 16:34 UTC, reum commented on telebot/sejong/news.py
> +    for element in news:
얍얍!

2016-11-22 16:34 UTC, reum commented on telebot/sejong/news.py
string.... ;ㅅ;

2016-11-22 16:35 UTC, reum commented on telebot/sejong/news.py
오키오키!

2016-11-22 16:36 UTC, reum commented on telebot/sejong/news.py
얍얍

2016-11-25 12:34 UTC, reum commented
수정했습니다! 다시 확인부탁해용 ㅎ

2016-11-25 12:40 UTC, reum commented
필요없는 코드 있길래 수정했어욤 ㅎㅎ

2016-11-26 01:07 UTC, sweetchipsw commented
머지 ㄱㄱ

2016-11-26 01:08 UTC, sweetchipsw commented on telebot/sejong/news.py
> +        except urllib.error.HTTPError as e:
실제 봇 만들때 익셉션 처리할때 exit 보다는 return {} 로 해서 프로그램이 꺼지게 하는건 어떨까요?

2016-11-26 01:12 UTC, sweetchipsw commented on telebot/sejong/news.py
> +        except urllib.error.HTTPError as e:
그리고 익셉션도 HTTPError 말고도 인터넷 연결 안될때 URLError 도 있기도 한데 어느 익셉션이든 하나로 묶을 수 있도록 except Exception, e: 로 묶는게 나을것 같네요.

2016-11-26 01:30 UTC, reum commented on telebot/sejong/news.py
> +        except urllib.error.HTTPError as e:
얍얍 수정하겠음! 기달!

2016-11-26 01:38 UTC, reum commented on telebot/sejong/news.py
> +        except urllib.error.HTTPError as e:
수정함!

2016-11-26 13:01 UTC, jsh95311 approved these changes

2016-11-26 13:16 UTC, jsh95311 commented
예외 발생시 str 반환, 정상 동작시 tuple 반환으로 했는데, 이렇게 할 경우 API caller 입장에서는 에러 여부를 반환 타입을 통해 알게되기 때문에 직관성이 떨어져 보입니다. 
공통적으로 드러나는 부분인만큼, #21 에서 다루도록 합시다.

2016-11-26 13:17 UTC, merged